apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-refresher
  namespace: oauth-refresher

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oauth-refresher
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oauth-refresher-cluster
subjects:
- kind: ServiceAccount
  name: oauth-refresher
  namespace: oauth-refresher
roleRef:
  kind: ClusterRole
  name: oauth-refresher
  apiGroup: rbac.authorization.k8s.io
