apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oauth-refresher.fullname" . }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "oauth-refresher.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "oauth-refresher.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "oauth-refresher.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "oauth-refresher.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
